### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by MarleneRamirez0731** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-MarleneRamirez0731#1]
![Infografia_Marlene_Osorio](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-MarleneRamirez0731/assets/112357070/a8299fe6-7549-4e3c-a2d4-deb0e522e60a)

**Comment by Daisy-GonzalezLita12** [comment]
20% de 20%, bien hecho.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
